tables:
  - name: employees
    extract: false
    source: oracle
    source_type: db  # possible values: db, files, api
    destination: bq

    # Table Info
    # timestamp_column: tdate
    # timestamp_format: 'YYYY-MM-DD HH24:MI:SS' # (Oracle native timestamps to be used only)
    incremental_column: employee_id
    incremental_type: id # possible values : id, timestamp

    # Query/Frequency info
    frequency: daily # (options: hourly, daily, weekly, monthly, yearly)
    query: "select * from employees"
    batch_size: 5000

    # destination_details
    gcp_project_id: turing-nature-374608
    gcp_bq_dataset_name: test_dataset
    target_table_name: test_employee_bq
    target_operation: a # (a: for append, t: for truncate)
  

